### ISSUE TITLE
Error while scanning an invalid directory

### ISSUE THREAD

**Issue by cjus** [Muslim-Idris/node-recdirreader#1]
First off thanks for this module. I do realize it's quite old. But I've encountered an issue and thought I'd reach out.

{"event":"error","error":"TypeError","stack":"TypeError: this._events.hasOwnProperty is not a function\n    at RecDirReader._emitError (/usr/src/app/node_modules/recdirreader/lib/RecDirReader.js:61:20)\n    at /usr/src/app/node_modules/recdirreader/lib/RecDirReader.js:88:12\n    at FSReqWrap.oncomplete (fs.js:135:15)"}

Here's the code I'm using: 

```js
  /**
  * @name readDirectory
  * @param {string} directoryPath - directory path
  * @return {object} promise
  */
  readDirectory(directoryPath) {
    return new Promise((resolve, reject) => {
      let found = [];
      recDirReader()
        .on('any', (file) => {
          found.push(file);
        })
        .scan(directoryPath)
        .on('end', () => {
          resolve(found);
        })
        .on('error', (err) => {
          reject(err);
        });
    });
  }
```

I'm expecting to detect the error once it's emitted - however, a type error prevents this when ` this._events.hasOwnProperty is not a function`.

**Comment by leeferwagen** [comment]
You're welcome @cjus. Thank you for reporting this issue. It should now be fixed with v0.1.4.
